BB_CONF_FRAGMENT_SUMMARY = "Boot with s6-linux-init running traditional sysvinit rc scripts."
BB_CONF_FRAGMENT_DESCRIPTION = "Selects s6-linux-init as init, with service management handled \
by traditional sysvinit initscripts rather than s6-rc. \
"

INIT_MANAGER = "s6-linux-init-sysvinit-rc"
