["getty-@DEVICE@"]
type = "longrun"
dependencies = [
    "init-dev",
]
down-signal = "SIGHUP"
run = """
#!/usr/bin/execlineb -P

exec -c
getty -L @SPEED@ @DEVICE@ @TERM@
"""

[init-tty]
type = "bundle"
contents = [
    "getty-@DEVICE@",
]

[ok-init]
type = "bundle"
contents = [
    "init-tty",
]
