["getty-@DEVICE@"]
type = "longrun"
dependencies = [
    "init-dev",
]
run = """
#!/usr/bin/execlineb -P

backtick -E GETTY { readlink -f /sbin/getty }
case -s -- $GETTY
{
  "*/busybox"
  {
    exec -c
    $GETTY -L @SPEED@ @DEVICE@ @TERM@
  }
}
exec -c
s6-setsid $GETTY -L @SPEED@ @DEVICE@ @TERM@
"""

[init-tty]
type = "bundle"
contents = [
    "getty-@DEVICE@",
]

[ok-init]
type = "bundle"
contents = [
    "init-tty",
]
