# SPDX-License-Identifier: MIT

[connman-srv]
type = "longrun"
dependencies = [
    "dbus-srv",
    "udev-settle",
    "wpa-supplicant-srv",
]
run = """\
#!/usr/bin/execlineb -P

connmand --nodaemon
"""

[ok-lan]
type = "bundle"
contents = [
    "connman-srv",
]
