# SPDX-License-Identifier: MIT

[connman-srv]
flag-recommended = true
type = "longrun"
dependencies = [
    "dbus-srv",
    "udev-trigger",
    "wpa-supplicant-srv",
]
run = """\
#!/usr/bin/execlineb -P

fdmove -c 2 1
connmand --nodaemon --noperror
"""

[ok-lan]
contents = [
    "connman-srv",
]
