#!/bin/sh -e

### This script is called once at boot time by rc.init, and is
### also called by the runleveld service every time the user
### requests a machine state change via telinit.
### Ideally, it should just be a call to the service manager.

test "$#" -gt 0 || { echo 'runlevel: fatal: too few arguments' 1>&2 ; exit 100 ; }

test -r /run/runlevel && PREVLEVEL=$(cat /run/runlevel) || PREVLEVEL=N
export PREVLEVEL
/etc/init.d/rc "$1" || true
test -w /run && echo "$1" >/run/runlevel
