# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-s6"
BBFILE_PATTERN_meta-s6 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-s6 = "6"

LAYERDEPENDS_meta-s6 = "core"
LAYERSERIES_COMPAT_meta-s6 = "wrynose"

BBFILES_DYNAMIC += "\
    core:${LAYERDIR}/bbappends/core/*/*/*.bbappend \
"
