CONFIGUREOPTS = " \
    --build=${BUILD_SYS} \
    --host=${HOST_SYS} \
    --target=${TARGET_SYS} \
    --prefix=${root_prefix} \
    --exec-prefix=${exec_prefix} \
    --dynlibdir=${libdir} \
    --includedir=${includedir} \
    --datadir=${sysconfdir} \
    --sysdepdir=${libdir}/${BPN}/sysdeps \
    --disable-pkgconfig \
    --enable-shared \
    ${EXTRA_OECONF} \
    ${PACKAGECONFIG_CONFARGS} \
"
CONFIGUREOPTS:append:class-target = "\
    --with-sysdeps=${STAGING_LIBDIR}/skalibs/sysdeps \
    --with-lib=${STAGING_LIBDIR} \
    --with-dynlib=${STAGING_LIBDIR} \
"
CONFIGUREOPTS:append:class-native = "\
    --with-sysdeps=${STAGING_LIBDIR_NATIVE}/skalibs/sysdeps \
    --with-lib=${STAGING_LIBDIR_NATIVE} \
    --with-dynlib=${STAGING_LIBDIR_NATIVE} \
"

skarnet_do_configure() {
	${S}/configure ${CONFIGUREOPTS}
	# Remove build path leakage
	sed -i -e '/^\/\* Generated by:/d' ${S}/src/include/${BPN}/config.h
}

skarnet_do_compile() {
	oe_runmake
}

skarnet_do_install() {
	oe_runmake DESTDIR=${D} install
	if [ -d ${D}${libdir} ]; then
		find ${D}${libdir} -name 'lib*.so' -exec chrpath -d {} \;
	fi
}

EXPORT_FUNCTIONS do_configure do_compile do_install

# pkgconfig support seems to have broken these dependencies which leak into targets
EXTRA_OEMAKE:append = " -W-lskarnet -W-ls6 -W-ls6dns -W-lexecline"
