# SPDX-License-Identifier: MIT

[mount-sys-kernel-debug]
type = "oneshot"
dependencies = [
    "mount-sys",
]
down = "s6-umount /sys/kernel/debug"
up = """
if -t { eltest -d /sys/kernel/debug }
s6-mount -t debugfs -o nosuid,nodev,noexec debugfs /sys/kernel/debug
"""
