# SPDX-License-Identifier: MIT

[mount-sys-fs-pstore]
type = "oneshot"
dependencies = [
    "mount-sys",
]
down = "s6-umount /sys/fs/pstore"
up = """
if { modprobe -abq pstore }
if { eltest -d /sys/fs/pstore }
s6-mount -t pstore -o nosuid,nodev,noexec pstore /sys/fs/pstore
"""
