# SPDX-License-Identifier: MIT

[mount-sys-fs-fuse-connections]
type = "oneshot"
dependencies = [
    "mount-sys",
]
down = "s6-umount /sys/fs/fuse/connections"
up = """
if { modprobe -abq fuse }
if { eltest -d /sys/fs/fuse/connections }
s6-mount -t fusectl -o nosuid,nodev,noexec fusectl /sys/fs/fuse/connections
"""
