# SPDX-License-Identifier: MIT

[mount-dev-pts]
dependencies = [
    "00",
]
type = "oneshot"
down = "s6-umount /dev/pts"
up = """
if -t { s6-mkdir -m 0755 /dev/pts }
s6-mount -t devpts -o nosuid,noexec,gid=5,mode=620 devpts /dev/pts
"""
