# SPDX-License-Identifier: MIT

[mount-sys-kernel-tracing]
type = "oneshot"
dependencies = [
    "mount-sys",
]
down = "s6-umount /sys/kernel/tracing"
up = """
if -t { eltest -d /sys/kernel/tracing }
s6-mount -t tracefs -o nosuid,nodev,noexec tracefs /sys/kernel/tracing
"""
