# SPDX-License-Identifier: MIT

[mount-sys-fs-bpf]
type = "oneshot"
dependencies = [
    "mount-sys",
]
down = "s6-umount /sys/fs/bpf"
up = """
if { eltest -d /sys/fs/bpf }
s6-mount -t bpf -o nosuid,nodev,noexec bpf /sys/fs/bpf
"""
