# SPDX-License-Identifier: MIT

[mount-var-volatile]
flag-essential = true
type = "oneshot"
dependencies = [
    "00",
]
down = "s6-umount /var/volatile"
up = """
if -t { eltest -d /var/volatile }
s6-mount -t tmpfs -o mode=1777,strictatime,nosuid,nodev,size=50%,nr_inodes=1m,inode64 tmpfs /var/volatile
"""
