# SPDX-License-Identifier: MIT

[rngseed]
flag-recommended = true
dependencies = [
    "00",
    "init-disks"
]
up = """
if -t { eltest -r /var/lib/rngseed/seed }
rngseed -r
"""
type = "oneshot"
down = """
if { s6-mkdir -m 0700 -p /var/lib/rngseed }
rngseed -w
"""
