# SPDX-License-Identifier: MIT

[wpa-supplicant-srv]
flag-recommended = true
type = "longrun"
dependencies = [
    "dbus-srv",
    "udev-trigger",
]
producer-for = "wpa-supplicant-log"
run = """\
#!/usr/bin/execlineb -P

fdmove -c 2 1
exec -c
wpa_supplicant -d -u -c/etc/wpa_supplicant.conf
"""

[wpa-supplicant-log]
flag-recommended = true
type = "longrun"
consumer-for = [
    "wpa-supplicant-srv",
]
dependencies = [
    "populate-volatile",
]
notification-fd = 3
pipeline-name = "wpa-supplicant-pipeline"
run = """
#!/usr/bin/execlineb -P

s6-envuidgid root
s6-envuidgid -g adm
s6-applyuidgid
exec -c
s6-log -d3 -- t s131072 n1 /var/log/wpa-supplicant
"""
