# SPDX-License-Identifier: MIT

[mount-dev-pts]
dependencies = [
    "mount-dev",
]
type = "oneshot"
down = "s6-umount /dev/pts"
up = """
if -t { redirfd -r 0 /proc/filesystems s6-grep -qF devpts }
if { s6-mkdir -m 0755 /dev/pts }
if { s6-mount -wt devpts -ogid=5,mode=620,ptmxmode=666 pts /dev/pts }
s6-ln -s -f pts/ptmx /dev/ptmx
"""
