# SPDX-License-Identifier: MIT

[mount-sys-kernel-config]
type = "oneshot"
dependencies = [
    "mount-sys",
]
down = "s6-umount /sys/kernel/config"
up = """
if -t { eltest -d /sys/kernel/config }
if -t { modprobe -abq configfs }
s6-mount -t configfs -o nosuid,nodev,noexec configfs /sys/kernel/config
"""
