# SPDX-License-Identifier: MIT

[ok-init]
contents = [
    "klogd",
    "mount-dev-pts",
    "mount-disks",
    "mount-sys-configfs",
    "mount-sys-debugfs",
    "rngseed",
    "syslogd",
]
type = "bundle"
